package com.example.mealer.Accounts;

// this class will store the complaints that a client has

public class ClientComplaints {
    private String complaint;
    // the ID are just the hash-value ID generated by the database
    private String clientID, cookID, complaintID;

    // to avoid JAVA reflection issues, need a no-parameter consructor
    public ClientComplaints() {
    }

    public ClientComplaints(String complaint, String clientID, String cookID) {
        this.complaint = complaint;
        this.clientID = clientID;
        this.cookID = cookID;
    }

    // getters and setters in order to check and reset values
    public String getComplaintID() {
        return complaintID;
    }

    public void setComplaintID(String complaintID) {
        this.complaintID = complaintID;
    }

    public String getComplaint() {
        return complaint;
    }

    public void setComplaint(String complaint) {
        this.complaint = complaint;
    }

    public String getClientID() {
        return clientID;
    }

    public void setClientID(String clientID) {
        this.clientID = clientID;
    }

    public String getCookID() {
        return cookID;
    }

    public void setCookID(String cookID) {
        this.cookID = cookID;
    }
}
